### Forecasting the Number of Future Service Requests

As requests vary seasonally, we plan to analyze past data on the frequency and types of requests in previous years or months to identify recurring patterns or anomalies. These forecasts will enable municipalities and service departments to anticipate periods of higher demand and plan accordingly. The outcome variable used would be the number of future service requests in a specific time frame, categorised by request type and origin

### Import Libraries

In [265]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline 
import matplotlib.pyplot as plt
import plotly.express as px
import sklearn
import statsmodels
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import TimeSeriesSplit, cross_val_score

In [266]:
clean_data = pd.read_csv("../Data/CleanedData_311_Dataset.csv")
clean_data.shape

(362893, 298)

In [267]:
clean_data.columns

Index(['_id', 'group_id', 'num_requests', 'parent_closed', 'status_code',
       'create_date_et', 'last_action_et', 'closed_date_et',
       'council_district', 'ward',
       ...
       'dept_simplified_Pittsburgh Water & Sewer Authority',
       'dept_simplified_Pittsburgh Water and Sewer Authority',
       'dept_simplified_Police', 'dept_simplified_Port Authority Transit',
       'dept_simplified_Public Safety', 'dept_simplified_SPIN Scooters',
       'dept_simplified_Sargent Electric', 'dept_simplified_School Guards',
       'dept_simplified_Scoobi',
       'dept_simplified_Urban Redevelopment Authority'],
      dtype='object', length=298)

In [268]:
clean_data.head()

,_id,group_id,num_requests,parent_closed,status_code,create_date_et,last_action_et,closed_date_et,council_district,ward,...,dept_simplified_Pittsburgh Water & Sewer Authority,dept_simplified_Pittsburgh Water and Sewer Authority,dept_simplified_Police,dept_simplified_Port Authority Transit,dept_simplified_Public Safety,dept_simplified_SPIN Scooters,dept_simplified_Sargent Electric,dept_simplified_School Guards,dept_simplified_Scoobi,dept_simplified_Urban Redevelopment Authority
0,97,626501,1,0,0,2022-04-24 09:56:00,2022-04-24 09:56:00,NaN,6.0,2.0,...,False,False,True,False,False,False,False,False,False,False
1,310,577909,1,0,3,2021-10-31 09:13:00,2021-11-30 09:21:00,NaN,7.0,11.0,...,False,False,False,False,False,False,False,False,False,False
2,376,620792,1,0,0,2022-04-01 07:33:00,2022-04-01 07:33:00,NaN,7.0,11.0,...,False,False,True,False,False,False,False,False,False,False
3,548,641351,1,0,0,2022-06-05 14:43:00,2022-06-05 14:43:00,NaN,7.0,11.0,...,False,False,True,False,False,False,False,False,False,False
4,793,569844,1,0,0,2021-09-30 11:42:00,2021-09-30 11:42:00,NaN,6.0,26.0,...,False,False,False,False,False,False,False,False,False,False

In [269]:
clean_data['create_date_et'] = pd.to_datetime(clean_data['create_date_et'])
clean_data['last_action_et'] = pd.to_datetime(clean_data['last_action_et'])
clean_data['closed_date_et'] = pd.to_datetime(clean_data['closed_date_et'])

### Creating Season Column

Winter: December, January, February 
Spring: March, April, May 
Summer: June, July, August
Fall: September, October, November

In [270]:
# Extract the month from 'create_date_et'
clean_data['month'] = clean_data['create_date_et'].dt.month

# Function to categorize the month into seasons
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    elif month in [9, 10, 11]:
        return 'Fall'

# Create the 'season' column based on the month
clean_data['season'] = clean_data['month'].apply(get_season)

clean_data['season'].value_counts()

season
Summer    109287
Spring     88420
Winter     87007
Fall       78179
Name: count, dtype: int64

In [271]:
# Collapse one-hot columns to single column values
clean_data['neighborhood'] = clean_data.filter(like='neighborhood_').idxmax(axis=1).str.replace('neighborhood_', '')
clean_data['category'] = clean_data.filter(like='category_').idxmax(axis=1).str.replace('category_', '')
clean_data['origin'] = clean_data.filter(like='origin_').idxmax(axis=1).str.replace('origin_', '')
clean_data['dept_simplified'] = clean_data.filter(like='dept_simplified_').idxmax(axis=1).str.replace('dept_simplified_', '')

### Without Time Series Cross Validation

#### Data Aggregation (by Seasons and Neighborbood)

In [272]:
# Group by month and request type to get the count of requests
season_requests_req = clean_data.groupby(
    ['season', 'neighborhood', 'category', 'origin']
).size().reset_index(name='request_count')
season_requests_req.head()

  season    neighborhood         category              origin  request_count
0   Fall  Allegheny West    Accessibility             Website              1
1   Fall  Allegheny West    Animal Issues       Control Panel              2
2   Fall  Allegheny West    Animal Issues  Report2Gov Website              1
3   Fall  Allegheny West    Animal Issues             Website              2
4   Fall  Allegheny West  Bicycle Parking             Website              1

In [273]:
season_model_neighborhood = pd.get_dummies(season_requests_req, 
                          columns=['season', 'neighborhood', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

In [274]:
season_model_neighborhood.head()

,request_count,season_Spring,season_Summer,season_Winter,neighborhood_Allentown,neighborhood_Arlington - Arlington Heights (Combined),neighborhood_Banksville,neighborhood_Bedford Dwellings,neighborhood_Beechview,neighborhood_Beltzhoover,...,category_Vacant Lot,category_Water Runoff in ROW,category_Weeds/Debris,origin_Email,origin_Report2Gov Android,origin_Report2Gov Website,origin_Report2Gov iOS,origin_Text Message,origin_Twitter,origin_Website
0,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

### Modeling

In [275]:
from sklearn.model_selection import train_test_split

X = season_model_neighborhood.drop(columns=['request_count'])
y = season_model_neighborhood['request_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [276]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_season_neighborhood = mean_squared_error(y_train, y_baseline)
baseline_rmse_season_neighborhood = np.sqrt(baseline_rmse_season_neighborhood)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_season_neighborhood}")

Baseline RMSE (Mean Model): 30.8380596439837

In [277]:
# Linear Regression Model
from sklearn.linear_model import LinearRegression

pipeline = make_pipeline(LinearRegression())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_linear_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_linear_neighborhood_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_linear_neighborhood_season.mean()}")

RMSE scores for each fold: [21.94459076 29.12248237 31.5292018  27.54581447 27.52377739]
Mean RMSE: 27.533173358454302

In [278]:
# Decision Tree Model
from sklearn.tree import DecisionTreeRegressor

pipeline = make_pipeline(DecisionTreeRegressor())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_dtree_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_neighborhood_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_neighborhood_season.mean()}")

RMSE scores for each fold: [39.18864682 29.57573066 35.7312919  45.53179909 36.88964784]
Mean RMSE: 37.38342326149912

In [279]:
# XGboost
from xgboost import XGBRegressor

pipeline = make_pipeline(XGBRegressor())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_xgboost_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_neighborhood_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_neighborhood_season.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [26.25715235 25.66881258 29.81810396 28.82193573 25.47243671]
Mean RMSE: 27.207688265894568

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Seasons and Department)

In [280]:
# Group by month and request type to get the count of requests
season_requests_req = clean_data.groupby(
    ['season', 'dept_simplified', 'category', 'origin']
).size().reset_index(name='request_count')
season_requests_req.head()

,season,dept_simplified,category,origin,request_count
0,Fall,911,"ADA Ramp, Installation",Email,1
1,Fall,911,"ADA Ramp, Installation",Website,310
2,Fall,911,Accessible Parking Application,Control Panel,55
3,Fall,911,Accessible Parking Application,Website,1
4,Fall,911,Ask Us/General FAQs,Website,2

In [281]:
season_model_dept = pd.get_dummies(season_requests_req, 
                          columns=['season', 'dept_simplified', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

### Modeling

In [282]:
X = season_model_dept.drop(columns=['request_count'])
y = season_model_dept['request_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [283]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_season_dept = mean_squared_error(y_train, y_baseline)
baseline_rmse_season_dept = np.sqrt(baseline_rmse_season_dept)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_season_dept}")

Baseline RMSE (Mean Model): 569.8247296433256

In [284]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_linear_dept_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_linear_dept_season.mean()}")

RMSE scores for each fold: [466.19495723 770.20221189 358.95956048 569.16176703 392.24327434]
Mean RMSE: 511.35235419319497

In [285]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_dept_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_dept_season.mean()}")

RMSE scores for each fold: [1184.61904756 1104.23917902  480.93058741 1232.88885962 1076.365933  ]
Mean RMSE: 1015.80872132396

In [286]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_dept_season}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_dept_season.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [808.3640501  755.89495798 311.6650596  826.71976056 607.54079081]
Mean RMSE: 662.0369238109126

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Month and Neighborbood)

In [287]:
# Group by month and request type to get the count of requests
month_requests_req = clean_data.groupby(
    ['month', 'neighborhood', 'category', 'origin']
).size().reset_index(name='request_count')
month_requests_req.head()

,month,neighborhood,category,origin,request_count
0,1,Allegheny West,Accessibility,Report2Gov Website,1
1,1,Allegheny West,Angle Iron,Website,1
2,1,Allegheny West,Animal Issues,Control Panel,1
3,1,Allegheny West,Animal Issues,Website,1
4,1,Allegheny West,Bicycle/Pedestrian Concerns,Control Panel,1

In [288]:
month_model_neighborhood = pd.get_dummies(month_requests_req, 
                          columns=['month', 'neighborhood', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

#### Modelling

In [289]:
X = month_model_neighborhood.drop(columns=['request_count'])
y = month_model_neighborhood['request_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [290]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_month_neighborhood = mean_squared_error(y_train, y_baseline)
baseline_rmse_month_neighborhood = np.sqrt(baseline_rmse_month_neighborhood)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_month_neighborhood}")

Baseline RMSE (Mean Model): 14.560043347482747

In [291]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform 5 fold cross-validation 
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_linear_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_linear_dept_month.mean()}")

RMSE scores for each fold: [12.15107446 12.94649844 13.4431722  15.49953691 11.45594645]
Mean RMSE: 13.099245692578046

In [292]:
# Decision Tree 
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_dept_month.mean()}")

RMSE scores for each fold: [19.91576311 22.40552371 17.37215622 20.45491244 20.85436758]
Mean RMSE: 20.200544612605285

In [293]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_dept_month.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [ 9.89337149  9.72814291 10.7600356  12.75804632  8.76573293]
Mean RMSE: 10.381065850012048

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Month and Department)

In [294]:
# Group by month and request type to get the count of requests
month_requests_req = clean_data.groupby(
    ['month', 'dept_simplified', 'category', 'origin']
).size().reset_index(name='request_count')
month_requests_req.head()

,month,dept_simplified,category,origin,request_count
0,1,911,"ADA Ramp, Installation",Control Panel,1
1,1,911,"ADA Ramp, Installation",Website,58
2,1,911,Accessible Parking Application,Control Panel,13
3,1,911,Building Maintenance,Website,1
4,1,911,Business Issues,Website,5

In [295]:
month_model_dept = pd.get_dummies(month_requests_req, 
                          columns=['month', 'dept_simplified', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

#### Modeling

In [296]:
X = month_model_dept.drop(columns=['request_count'])
y = month_model_dept['request_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [297]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_month_dept = mean_squared_error(y_train, y_baseline)
baseline_rmse_month_dept = np.sqrt(baseline_rmse_month_dept)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_month_dept}")

Baseline RMSE (Mean Model): 234.7196947206209

In [298]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_linear_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_linear_dept_month.mean()}")

RMSE scores for each fold: [153.31285711 141.82744775 133.40480252 288.15923055 297.41402992]
Mean RMSE: 202.82367357037583

In [299]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_dept_month.mean()}")

RMSE scores for each fold: [432.46916872 336.97167579 409.37868209 368.01103728 319.60498168]
Mean RMSE: 373.28710911304745

In [300]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_dept_month.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [116.93865663 117.92075182 129.79046364 199.49983357 241.5838283 ]
Mean RMSE: 161.1467067922899

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Month and Department)

In [301]:
# Group by month and request type to get the count of requests
month_requests_req = clean_data.groupby(
    ['month', 'dept_simplified', 'category', 'origin']
).size().reset_index(name='request_count')
month_requests_req.head()

,month,dept_simplified,category,origin,request_count
0,1,911,"ADA Ramp, Installation",Control Panel,1
1,1,911,"ADA Ramp, Installation",Website,58
2,1,911,Accessible Parking Application,Control Panel,13
3,1,911,Building Maintenance,Website,1
4,1,911,Business Issues,Website,5

In [302]:
month_model_dept = pd.get_dummies(month_requests_req, 
                          columns=['month', 'dept_simplified', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

#### Modeling

In [303]:
X = month_model_dept.drop(columns=['request_count'])
y = month_model_dept['request_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [304]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_month_dept = mean_squared_error(y_train, y_baseline)
baseline_rmse_month_dept = np.sqrt(baseline_rmse_month_dept)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_month_dept}")

Baseline RMSE (Mean Model): 234.7196947206209

In [305]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_linear_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_linear_dept_month.mean()}")

RMSE scores for each fold: [153.31285711 141.82744775 133.40480252 288.15923055 297.41402992]
Mean RMSE: 202.82367357037583

In [306]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_dept_month.mean()}")

RMSE scores for each fold: [432.51692609 336.99940164 413.38348859 367.96888299 319.17076325]
Mean RMSE: 374.00789251316803

In [307]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform 5 fold cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_dept_month.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [116.93865663 117.92075182 129.79046364 199.49983357 241.5838283 ]
Mean RMSE: 161.1467067922899

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

### Consolidating RMSE [Without Time Series Split Cross Validation]

In [308]:
# Comparing RMSE of different models
rmse_scores = {
    'Linear Neighborhood Season': rmse_scores_linear_neighborhood_season,
    'Decision Tree Neighborhood Season': rmse_scores_dtree_neighborhood_season,
    'XGBoost Neighborhood Season': rmse_scores_xgboost_neighborhood_season,
    'Linear Department Season': rmse_scores_linear_dept_season,
    'Decision Tree Department Season': rmse_scores_dtree_dept_season,
    'XGBoost Department Season': rmse_scores_xgboost_dept_season,
    'Linear Neighborhood Month': rmse_scores_linear_dept_month,
    'Decision Tree Neighborhood Month': rmse_scores_dtree_dept_month,
    'XGBoost Neighborhood Month': rmse_scores_xgboost_dept_month,
    'Linear Department Month': rmse_scores_linear_dept_month,
    'Decision Tree Department Month': rmse_scores_dtree_dept_month,
    'XGBoost Department Month': rmse_scores_xgboost_dept_month
}
# Convert to DataFrame for better visualization
rmse_df = pd.DataFrame(rmse_scores)
# Calculate mean RMSE for each model
mean_rmse = {key: np.mean(value) for key, value in rmse_scores.items()}
# Create a DataFrame for better visualization
rmse_summary = pd.DataFrame([
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Neighborhood Season'], 'Better than Baseline?': mean_rmse['Linear Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Neighborhood Season'], 'Better than Baseline?': mean_rmse['Decision Tree Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Neighborhood Season'], 'Better than Baseline?': mean_rmse['XGBoost Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Department Season'], 'Better than Baseline?': mean_rmse['Linear Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Department Season'], 'Better than Baseline?': mean_rmse['Decision Tree Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Department Season'], 'Better than Baseline?': mean_rmse['XGBoost Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Neighborhood Month'], 'Better than Baseline?': mean_rmse['Linear Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Neighborhood Month'], 'Better than Baseline?': mean_rmse['Decision Tree Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Neighborhood Month'], 'Better than Baseline?': mean_rmse['XGBoost Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Department Month'], 'Better than Baseline?': mean_rmse['Linear Department Month'] < baseline_rmse_month_dept},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Department Month'], 'Better than Baseline?': mean_rmse['Decision Tree Department Month'] < baseline_rmse_month_dept},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Department Month'], 'Better than Baseline?': mean_rmse['XGBoost Department Month'] < baseline_rmse_month_dept}
])

rmse_summary

   Grouping          Type          Model    Mean RMSE  Better than Baseline?
0    Season  Neighborhood         Linear    27.533173                   True
1    Season  Neighborhood  Decision Tree    37.383423                  False
2    Season  Neighborhood        XGBoost    27.207688                   True
3    Season    Department         Linear   511.352354                   True
4    Season    Department  Decision Tree  1015.808721                  False
5    Season    Department        XGBoost   662.036924                  False
6     Month  Neighborhood         Linear   202.823674                  False
7     Month  Neighborhood  Decision Tree   374.007893                  False
8     Month  Neighborhood        XGBoost   161.146707                  False
9     Month    Department         Linear   202.823674                   True
10    Month    Department  Decision Tree   374.007893                  False
11    Month    Department        XGBoost   161.146707                   True

### Modeling With Time Series Cross Validation

#### Data Aggregation (by Seasons and Neighborbood)

In [309]:
# Sort clean_data by opened_date
clean_data = clean_data.sort_values(by='create_date_et')

In [310]:
# Group by month and request type to get the count of requests
season_requests_req = clean_data.groupby(
    ['season', 'neighborhood', 'category', 'origin']
).size().reset_index(name='request_count')
season_requests_req.head()

  season    neighborhood         category              origin  request_count
0   Fall  Allegheny West    Accessibility             Website              1
1   Fall  Allegheny West    Animal Issues       Control Panel              2
2   Fall  Allegheny West    Animal Issues  Report2Gov Website              1
3   Fall  Allegheny West    Animal Issues             Website              2
4   Fall  Allegheny West  Bicycle Parking             Website              1

In [311]:
season_model_neighborhood = pd.get_dummies(season_requests_req, 
                          columns=['season', 'neighborhood', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

In [312]:
season_model_neighborhood.head()

,request_count,season_Spring,season_Summer,season_Winter,neighborhood_Allentown,neighborhood_Arlington - Arlington Heights (Combined),neighborhood_Banksville,neighborhood_Bedford Dwellings,neighborhood_Beechview,neighborhood_Beltzhoover,...,category_Vacant Lot,category_Water Runoff in ROW,category_Weeds/Debris,origin_Email,origin_Report2Gov Android,origin_Report2Gov Website,origin_Report2Gov iOS,origin_Text Message,origin_Twitter,origin_Website
0,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

#### Modeling

In [313]:
from sklearn.model_selection import train_test_split

X = season_model_neighborhood.drop(columns=['request_count'])
y = season_model_neighborhood['request_count']

tscv = TimeSeriesSplit(n_splits=5)

In [314]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_season_neighborhood = mean_squared_error(y_train, y_baseline)
baseline_rmse_season_neighborhood = np.sqrt(baseline_rmse_season_neighborhood)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_season_neighborhood}")

Baseline RMSE (Mean Model): 234.7196947206209

In [315]:
# Linear Regression Model
pipe = make_pipeline(
    LinearRegression()
)

# Perform time series cross-validation
scores = cross_val_score(pipe, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_linear_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_linear_neighborhood_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_linear_neighborhood_season.mean())

pipeline = make_pipeline(LinearRegression())

RMSE Cross-validated scores (time-aware): [25.24486579 25.86081209 25.42779267 41.58686729 31.17778453]

Mean RMSE: 29.859624472283127

In [316]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_dtree_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_dtree_neighborhood_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_dtree_neighborhood_season.mean())

RMSE Cross-validated scores (time-aware): [24.97846952 19.55020732 19.35835111 30.42973277 27.70946671]

Mean RMSE: 24.40524548377523

In [317]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_xgboost_neighborhood_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_xgboost_neighborhood_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_xgboost_neighborhood_season.mean())

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE Cross-validated scores (time-aware): [22.57736874 19.74847715 20.7184068  33.40103517 22.39139302]

Mean RMSE: 23.76733617640749

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Seasons and Department)

In [318]:
# Sort clean_data by opened_date
clean_data = clean_data.sort_values(by='create_date_et')

In [319]:
# Group by month and request type to get the count of requests
season_requests_req = clean_data.groupby(
    ['season', 'dept_simplified', 'category', 'origin']
).size().reset_index(name='request_count')
season_requests_req.head()

,season,dept_simplified,category,origin,request_count
0,Fall,911,"ADA Ramp, Installation",Email,1
1,Fall,911,"ADA Ramp, Installation",Website,310
2,Fall,911,Accessible Parking Application,Control Panel,55
3,Fall,911,Accessible Parking Application,Website,1
4,Fall,911,Ask Us/General FAQs,Website,2

In [320]:
season_model_dept = pd.get_dummies(season_requests_req, 
                          columns=['season', 'dept_simplified', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

### Modeling

In [321]:
X = season_model_dept.drop(columns=['request_count'])
y = season_model_dept['request_count']
tscv = TimeSeriesSplit(n_splits=5)

In [322]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_season_dept = mean_squared_error(y_train, y_baseline)
baseline_rmse_season_dept = np.sqrt(baseline_rmse_season_dept)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_season_dept}")

Baseline RMSE (Mean Model): 234.7196947206209

In [323]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_linear_dept_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_linear_dept_season.mean())

RMSE Cross-validated scores (time-aware): [368.7050803  534.4126954  440.86596038 556.48691325 752.69415768]

Mean RMSE: 530.632961402112

In [324]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_dtree_dept_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_dtree_dept_season.mean())

RMSE Cross-validated scores (time-aware): [480.74941311 193.08410647 163.93607262 327.40494804 564.50575927]

Mean RMSE: 345.9360599015041

In [325]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_season = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_xgboost_dept_season)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_xgboost_dept_season.mean())

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE Cross-validated scores (time-aware): [426.37824317 319.14533083 242.59911795 372.6282707  574.07948056]

Mean RMSE: 386.96608864182224

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Month and Neighborbood)

In [326]:
# Sort clean_data by opened_date
clean_data = clean_data.sort_values(by='create_date_et')

In [327]:
# Group by month and request type to get the count of requests
month_requests_req = clean_data.groupby(
    ['month', 'neighborhood', 'category', 'origin']
).size().reset_index(name='request_count')
month_requests_req.head()

,month,neighborhood,category,origin,request_count
0,1,Allegheny West,Accessibility,Report2Gov Website,1
1,1,Allegheny West,Angle Iron,Website,1
2,1,Allegheny West,Animal Issues,Control Panel,1
3,1,Allegheny West,Animal Issues,Website,1
4,1,Allegheny West,Bicycle/Pedestrian Concerns,Control Panel,1

In [328]:
month_model_neighborhood = pd.get_dummies(month_requests_req, 
                          columns=['month', 'neighborhood', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

#### Modelling

In [329]:
X = month_model_neighborhood.drop(columns=['request_count'])
y = month_model_neighborhood['request_count']
tscv = TimeSeriesSplit(n_splits=5)

In [330]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_month_neighborhood = mean_squared_error(y_train, y_baseline)
baseline_rmse_month_neighborhood = np.sqrt(baseline_rmse_month_neighborhood)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_month_neighborhood}")

Baseline RMSE (Mean Model): 234.7196947206209

In [331]:
# Linear Regression Model
pipe = make_pipeline(
    LinearRegression()
)

# Perform time series cross-validation
scores = cross_val_score(pipe, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_linear_dept_month)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_linear_dept_month.mean())

pipeline = make_pipeline(LinearRegression())

RMSE Cross-validated scores (time-aware): [11.24645047 13.29169243 11.24043603 10.94642    11.0763563 ]

Mean RMSE: 11.560271044997439

In [332]:
# Decision Tree 
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_dtree_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_dtree_dept_month.mean()}")

RMSE scores for each fold: [237.13387632 251.42305064 210.57668559 261.14819631 293.10548459]
Mean RMSE: 250.677458690103

In [333]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print(f"RMSE scores for each fold: {rmse_scores_xgboost_dept_month}")
# Print mean RMSE
print(f"Mean RMSE: {rmse_scores_xgboost_dept_month.mean()}")

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE scores for each fold: [173.17416946 123.59838013 110.41709365 272.57785585 243.04702316]
Mean RMSE: 184.56290445098418

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

#### Data Aggregation (by Month and Department)

In [334]:
# Sort clean_data by opened_date
clean_data = clean_data.sort_values(by='create_date_et')

In [335]:
# Group by month and request type to get the count of requests
month_requests_req = clean_data.groupby(
    ['month', 'dept_simplified', 'category', 'origin']
).size().reset_index(name='request_count')
month_requests_req.head()

,month,dept_simplified,category,origin,request_count
0,1,911,"ADA Ramp, Installation",Control Panel,1
1,1,911,"ADA Ramp, Installation",Website,58
2,1,911,Accessible Parking Application,Control Panel,13
3,1,911,Building Maintenance,Website,1
4,1,911,Business Issues,Website,5

In [336]:
month_model_dept = pd.get_dummies(month_requests_req, 
                          columns=['month', 'dept_simplified', 'category', 'origin'], 
                          drop_first=True, 
                          sparse=True)

#### Modeling

In [337]:
X = month_model_dept.drop(columns=['request_count'])
y = month_model_dept['request_count']
tscv = TimeSeriesSplit(n_splits=5)

In [338]:
# Baseline Model (Mean of y_train)
y_baseline = np.full_like(y_train, y_train.mean())

# RMSE for Baseline Model
baseline_rmse_month_dept = mean_squared_error(y_train, y_baseline)
baseline_rmse_month_dept = np.sqrt(baseline_rmse_month_dept)
print(f"Baseline RMSE (Mean Model): {baseline_rmse_month_dept}")

Baseline RMSE (Mean Model): 234.7196947206209

In [339]:
# Linear Regression Model
pipeline = make_pipeline(LinearRegression())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_linear_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_linear_dept_month)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_linear_dept_month.mean())

RMSE Cross-validated scores (time-aware): [158.31068108 221.24028561 206.92770248 159.22101937 132.6032072 ]

Mean RMSE: 175.66057914926785

In [340]:
# Decision Tree Model
pipeline = make_pipeline(DecisionTreeRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_dtree_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_dtree_dept_month)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_dtree_dept_month.mean())

RMSE Cross-validated scores (time-aware): [270.19114592 294.21918908 305.91613333 325.14025311 299.04720238]

Mean RMSE: 298.90278476437885

In [341]:
# XGboost
pipeline = make_pipeline(XGBRegressor())

# Perform time series cross-validation
scores = cross_val_score(pipeline, X, y, cv=tscv, scoring='neg_mean_squared_error')

rmse_scores_xgboost_dept_month = np.sqrt(-scores)

# Print RMSE for each fold
print("RMSE Cross-validated scores (time-aware):", rmse_scores_xgboost_dept_month)
# Print mean RMSE
print("\nMean RMSE:", rmse_scores_xgboost_dept_month.mean())

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

RMSE Cross-validated scores (time-aware): [232.80544452 223.34253227 167.86196315 124.95533968  90.6081396 ]

Mean RMSE: 167.91468384216262

/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/opt/anaconda3/envs/new/lib/python3.12/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

### Consolidating RMSE [With Time Series Split Cross Validation]

In [342]:
# Comparing RMSE of different models
rmse_scores = {
    'Linear Neighborhood Season': rmse_scores_linear_neighborhood_season,
    'Decision Tree Neighborhood Season': rmse_scores_dtree_neighborhood_season,
    'XGBoost Neighborhood Season': rmse_scores_xgboost_neighborhood_season,
    'Linear Department Season': rmse_scores_linear_dept_season,
    'Decision Tree Department Season': rmse_scores_dtree_dept_season,
    'XGBoost Department Season': rmse_scores_xgboost_dept_season,
    'Linear Neighborhood Month': rmse_scores_linear_dept_month,
    'Decision Tree Neighborhood Month': rmse_scores_dtree_dept_month,
    'XGBoost Neighborhood Month': rmse_scores_xgboost_dept_month,
    'Linear Department Month': rmse_scores_linear_dept_month,
    'Decision Tree Department Month': rmse_scores_dtree_dept_month,
    'XGBoost Department Month': rmse_scores_xgboost_dept_month
}
# Convert to DataFrame for better visualization
rmse_df = pd.DataFrame(rmse_scores)
# Calculate mean RMSE for each model
mean_rmse = {key: np.mean(value) for key, value in rmse_scores.items()}
# Create a DataFrame for better visualization
rmse_summary = pd.DataFrame([
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Neighborhood Season'], 'Better than Baseline?': mean_rmse['Linear Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Neighborhood Season'], 'Better than Baseline?': mean_rmse['Decision Tree Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Neighborhood', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Neighborhood Season'], 'Better than Baseline?': mean_rmse['XGBoost Neighborhood Season'] < baseline_rmse_season_neighborhood},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Department Season'], 'Better than Baseline?': mean_rmse['Linear Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Department Season'], 'Better than Baseline?': mean_rmse['Decision Tree Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Season', 'Type': 'Department', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Department Season'], 'Better than Baseline?': mean_rmse['XGBoost Department Season'] < baseline_rmse_season_dept},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Neighborhood Month'], 'Better than Baseline?': mean_rmse['Linear Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Neighborhood Month'], 'Better than Baseline?': mean_rmse['Decision Tree Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Neighborhood', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Neighborhood Month'], 'Better than Baseline?': mean_rmse['XGBoost Neighborhood Month'] < baseline_rmse_month_neighborhood},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'Linear', 'Mean RMSE': mean_rmse['Linear Department Month'], 'Better than Baseline?': mean_rmse['Linear Department Month'] < baseline_rmse_month_dept},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'Decision Tree', 'Mean RMSE': mean_rmse['Decision Tree Department Month'], 'Better than Baseline?': mean_rmse['Decision Tree Department Month'] < baseline_rmse_month_dept},
    {'Grouping': 'Month', 'Type': 'Department', 'Model': 'XGBoost', 'Mean RMSE': mean_rmse['XGBoost Department Month'], 'Better than Baseline?': mean_rmse['XGBoost Department Month'] < baseline_rmse_month_dept}
])

rmse_summary

   Grouping          Type          Model   Mean RMSE  Better than Baseline?
0    Season  Neighborhood         Linear   29.859624                   True
1    Season  Neighborhood  Decision Tree   24.405245                   True
2    Season  Neighborhood        XGBoost   23.767336                   True
3    Season    Department         Linear  530.632961                  False
4    Season    Department  Decision Tree  345.936060                  False
5    Season    Department        XGBoost  386.966089                  False
6     Month  Neighborhood         Linear  175.660579                   True
7     Month  Neighborhood  Decision Tree  298.902785                  False
8     Month  Neighborhood        XGBoost  167.914684                   True
9     Month    Department         Linear  175.660579                   True
10    Month    Department  Decision Tree  298.902785                  False
11    Month    Department        XGBoost  167.914684                   True